import { 
  Calculator, Atom, BookOpen, Binary, Cpu, Network, Database, 
  Code2, LineChart, Briefcase, ShieldCheck, 
  CheckCircle2, AlertTriangle, Lock, Unlock, X, Info,
  GraduationCap, ChevronRight, Layers, Sparkles, Filter,
  Building2, FlaskConical, Zap, Wrench, Microscope, ArrowLeft, Radio, FileText
} from 'lucide-react';
import React from 'react';

// --- Base de Datos Multi-Carrera adaptada ---
export const planesData = {
  sistemas: {
    id: 'sistemas',
    name: 'Ingeniería en Sistemas',
    shortName: 'Sistemas',
    requiredElectiveHours: 40,
    years: 5,
    icon: React.createElement(Code2, { className: "w-8 h-8" }),
    color: 'from-[#8BAA91] to-[#7CC2A8]',
    curriculum: [
      { id: "utn_am1", year: 1, semester: "1º Cuatrimestre", name: "Análisis Matemático I", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "utn_aga", year: 1, semester: "1º Cuatrimestre", name: "Álgebra y Geometría Analítica", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "sis_5", year: 1, semester: "1º Cuatrimestre", name: "Lógica y Estructuras Discretas", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "sis_6", year: 1, semester: "2º Cuatrimestre", name: "Algoritmo y Estructura de Datos", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "sis_7", year: 1, semester: "2º Cuatrimestre", name: "Arquitectura de Computadoras", weekly_hours: 4, total_hours: 96, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "sis_8", year: 1, semester: "2º Cuatrimestre", name: "Sistemas y Procesos de Negocio", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "utn_fis1", year: 1, semester: "2º Cuatrimestre", name: "Física I", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "utn_ing1", year: 1, semester: "2º Cuatrimestre", name: "Inglés I", weekly_hours: 2, total_hours: 48, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "sis_16", year: 2, semester: "Anual", name: "Análisis de Sistemas de Información", weekly_hours: 6, total_hours: 144, estado: "pendiente", regulares: ["sis_6", "sis_8"], aprobadas: [] },
      { id: "utn_am2", year: 2, semester: "1º Cuatrimestre", name: "Análisis Matemático II", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["utn_am1", "utn_aga"], aprobadas: [] },
      { id: "sis_13", year: 2, semester: "1º Cuatrimestre", name: "Sintaxis y Semántica de los Lenguajes", weekly_hours: 4, total_hours: 96, estado: "pendiente", regulares: ["sis_5", "sis_6"], aprobadas: [] },
      { id: "utn_ing_soc", year: 2, semester: "1º Cuatrimestre", name: "Ingeniería y Sociedad", weekly_hours: 2, total_hours: 48, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "utn_ing2", year: 2, semester: "1º Cuatrimestre", name: "Inglés II", weekly_hours: 2, total_hours: 48, estado: "pendiente", regulares: ["utn_ing1"], aprobadas: [] },
      { id: "utn_fis2", year: 2, semester: "2º Cuatrimestre", name: "Física II", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["utn_am1", "utn_fis1"], aprobadas: [] },
      { id: "sis_14", year: 2, semester: "2º Cuatrimestre", name: "Paradigmas de Programación", weekly_hours: 4, total_hours: 96, estado: "pendiente", regulares: ["sis_5", "sis_6"], aprobadas: [] },
      { id: "sis_15", year: 2, semester: "2º Cuatrimestre", name: "Sistemas Operativos", weekly_hours: 4, total_hours: 96, estado: "pendiente", regulares: ["sis_7"], aprobadas: [] },
      { id: "sis_23", year: 3, semester: "Anual", name: "Diseño de Sistemas de Información", weekly_hours: 6, total_hours: 144, estado: "pendiente", regulares: ["sis_14", "sis_16"], aprobadas: ["utn_ing1", "sis_6", "sis_8"] },
      { id: "utn_prob", year: 3, semester: "1º Cuatrimestre", name: "Probabilidad y Estadística", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: ["utn_am1", "utn_aga"], aprobadas: [] },
      { id: "utn_econo", year: 3, semester: "1º Cuatrimestre", name: "Economía", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: [], aprobadas: ["utn_am1", "utn_aga"] },
      { id: "sis_19", year: 3, semester: "1º Cuatrimestre", name: "Base de Datos", weekly_hours: 4, total_hours: 96, estado: "pendiente", regulares: ["sis_13", "sis_16"], aprobadas: ["sis_5", "sis_6"] },
      { id: "sis_21", year: 3, semester: "1º Cuatrimestre", name: "Comunicación de Datos", weekly_hours: 4, total_hours: 96, estado: "pendiente", regulares: [], aprobadas: ["utn_fis1", "sis_7"] },
      { id: "sis_20", year: 3, semester: "2º Cuatrimestre", name: "Desarrollo de Software", weekly_hours: 4, total_hours: 96, estado: "pendiente", regulares: ["sis_14", "sis_16"], aprobadas: ["sis_5", "sis_6"] },
      { id: "sis_22", year: 3, semester: "2º Cuatrimestre", name: "Análisis Numérico", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: ["utn_am2"], aprobadas: ["utn_am1", "utn_aga"] },
      { id: "sis_993", year: 3, semester: "Electiva", name: "Materias Electivas", weekly_hours: 4, total_hours: 96, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "sis_37", year: 4, semester: "1º Cuatrimestre", name: "Seminario Integrador (opcional)", weekly_hours: 4, total_hours: 96, estado: "pendiente", regulares: ["sis_15", "sis_19", "sis_20"], aprobadas: ["sis_5", "sis_6", "sis_7", "sis_8"] },
      { id: "sis_30", year: 4, semester: "Anual", name: "Administración de Sistemas de Información", weekly_hours: 6, total_hours: 144, estado: "pendiente", regulares: ["utn_econo", "sis_23"], aprobadas: ["sis_16"] },
      { id: "sis_25", year: 4, semester: "Anual", name: "Ingeniería y Calidad de Software", weekly_hours: 6, total_hours: 72, estado: "pendiente", regulares: ["sis_19", "sis_20", "sis_23"], aprobadas: ["sis_13", "sis_14"] },
      { id: "utn_legis", year: 4, semester: "1º Cuatrimestre", name: "Legislación", weekly_hours: 2, total_hours: 48, estado: "pendiente", regulares: ["utn_ing_soc"], aprobadas: [] },
      { id: "sis_27", year: 4, semester: "1º Cuatrimestre", name: "Investigación Operativa", weekly_hours: 4, total_hours: 96, estado: "pendiente", regulares: ["utn_prob", "sis_22"], aprobadas: [] },
      { id: "sis_28", year: 4, semester: "1º Cuatrimestre", name: "Simulación", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: ["utn_prob"], aprobadas: ["utn_am2"] },
      { id: "sis_26", year: 4, semester: "2º Cuatrimestre", name: "Redes de Datos", weekly_hours: 4, total_hours: 96, estado: "pendiente", regulares: ["sis_15", "sis_21"], aprobadas: [] },
      { id: "sis_29", year: 4, semester: "2º Cuatrimestre", name: "Tecnología para la Automatización", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: ["utn_fis2", "sis_22"], aprobadas: ["utn_am2"] },
      { id: "sis_994", year: 4, semester: "Electiva", name: "Materias Electivas", weekly_hours: 6, total_hours: 144, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "sis_36", year: 5, semester: "Anual", name: "Proyecto Final", weekly_hours: 6, total_hours: 144, estado: "pendiente", regulares: ["sis_25", "sis_26", "sis_30"], aprobadas: ["utn_ing2", "sis_20", "sis_23"] },
      { id: "sis_33", year: 5, semester: "1º Cuatrimestre", name: "Sistemas de Gestión", weekly_hours: 4, total_hours: 96, estado: "pendiente", regulares: ["utn_econo", "sis_27"], aprobadas: ["sis_23"] },
      { id: "sis_34", year: 5, semester: "1º Cuatrimestre", name: "Gestión Gerencial", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: ["utn_legis", "sis_30"], aprobadas: ["utn_econo"] },
      { id: "sis_35", year: 5, semester: "1º Cuatrimestre", name: "Seguridad en los Sistemas de Información", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: ["sis_26", "sis_30"], aprobadas: ["sis_20", "sis_21"] },
      { id: "sis_31", year: 5, semester: "2º Cuatrimestre", name: "Inteligencia Artificial", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: ["sis_28"], aprobadas: ["utn_prob", "sis_22"] },
      { id: "sis_32", year: 5, semester: "2º Cuatrimestre", name: "Ciencia de Datos", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: ["sis_28"], aprobadas: ["utn_prob", "sis_19"] },
      { id: "sis_995", year: 5, semester: "Electiva", name: "Materias Electivas", weekly_hours: 10, total_hours: 240, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "sis_99056", year: 3, semester: "2° Cuatrimestre", name: "Administración de Proyectos", weekly_hours: 8, total_hours: 0, estado: "pendiente", regulares: ["sis_16"], aprobadas: ["sis_8"], docente: "Colombo, Mónica y Lastra, Graciela", horario: "Lunes 21:15 a 23:30 y viernes 19:00 a 22:45", rendir: ["sis_8"], isElectiva: true },
      { id: "sis_99057", year: 3, semester: "2° Cuatrimestre", name: "Computación Paralela", weekly_hours: 8, total_hours: 0, estado: "pendiente", regulares: ["sis_15"], aprobadas: ["sis_7", "sis_14"], docente: "Bianchini, Germán y Caymes Scutari, Paola", horario: "Martes y Viernes 14:30 a 17:30", rendir: ["sis_14", "sis_7"], isElectiva: true },
      { id: "sis_99058", year: 4, semester: "2° Cuatrimestre", name: "Informática Industrial", weekly_hours: 8, total_hours: 0, estado: "pendiente", regulares: ["sis_19", "sis_27"], aprobadas: ["sis_14", "sis_16"], docente: "Nicotra, Lucas y Poquet, Gustavo", horario: "Martes 14:30 a 19:00, Viernes 17:30 a 19:00", rendir: ["sis_14", "sis_16"], isElectiva: true },
      { id: "sis_99059", year: 4, semester: "2° Cuatrimestre", name: "Arquitectura de Microservicios", weekly_hours: 8, total_hours: 0, estado: "pendiente", regulares: ["sis_20"], aprobadas: ["sis_6", "sis_14"], docente: "Marsollier, Néstor y Ceccoli, Andres", horario: "Lunes y Jueves de 19:00 a 22:00", rendir: ["sis_6", "sis_14"], isElectiva: true },
      { id: "sis_99060", year: 4, semester: "2° Cuatrimestre", name: "Base de Datos Avanzadas", weekly_hours: 8, total_hours: 0, estado: "pendiente", regulares: ["sis_15", "sis_19"], aprobadas: ["sis_6", "sis_7"], docente: "Bloise, Leonardo y Rey, Daniel", horario: "Martes 16:00 a 19:00, Miércoles 19:00 a 22:00", rendir: ["sis_15", "sis_19"], isElectiva: true },
      { id: "sis_99061", year: 4, semester: "2° Cuatrimestre", name: "Desarrollo de Software Dirigido por Modelos", weekly_hours: 6, total_hours: 0, estado: "pendiente", regulares: ["sis_19"], aprobadas: ["sis_14", "sis_16"], isElectiva: true },
      { id: "sis_99062", year: 4, semester: "2° Cuatrimestre", name: "Gobierno Digital e Innovación", weekly_hours: 6, total_hours: 0, estado: "pendiente", regulares: ["sis_16"], aprobadas: ["sis_8"], docente: "Rotella, Carina y Bosin, Marcela", horario: "Lunes y Jueves 16:45 a 19:00", rendir: ["sis_8"], isElectiva: true },
      { id: "sis_99063", year: 4, semester: "Sin especificar", name: "Diseño de Experiencia de Usuario (UX)", weekly_hours: 6, total_hours: 0, estado: "pendiente", regulares: ["sis_23"], aprobadas: ["sis_16"], docente: "Rotella, Carina y Rotella, Andrea", horario: "Sábado 8:30 a 13:00", rendir: ["sis_16"], isElectiva: true },
      { id: "sis_99064", year: 5, semester: "1° Cuatrimestre", name: "Seguridad en Redes", weekly_hours: 6, total_hours: 0, estado: "pendiente", regulares: [], aprobadas: [], isElectiva: true },
      { id: "sis_99065", year: 5, semester: "2° Cuatrimestre", name: "Redes Neuronales Profundas", weekly_hours: 8, total_hours: 0, estado: "pendiente", regulares: ["utn_ing1", "sis_31"], aprobadas: ["sis_6", "sis_22"], isElectiva: true },
      { id: "sis_99066", year: 5, semester: "2° Cuatrimestre", name: "Administración de Servicios en Linux", weekly_hours: 8, total_hours: 0, estado: "pendiente", regulares: ["sis_15", "sis_26"], aprobadas: ["sis_21"], docente: "Faccio, Sergio y Edera, Gabriel", horario: "Miércoles y jueves 19:00 a 22:00", rendir: ["sis_21"], isElectiva: true },
      { id: "sis_99067", year: 5, semester: "2° Cuatrimestre", name: "Evaluación e Innovación de Tecnología desde la perspectiva CTS", weekly_hours: 6, total_hours: 0, estado: "pendiente", regulares: ["utn_ing_soc", "utn_econo"], aprobadas: ["sis_8"], docente: "Moralejo, Raúl y Manino, Gustavo", horario: "Miércoles 14:30 a 19:00", rendir: ["sis_8"], isElectiva: true },
      { id: "sis_99068", year: 5, semester: "Sin especificar", name: "Taller de Auditoría en Sistemas de Información", weekly_hours: 6, total_hours: 0, estado: "pendiente", regulares: [], aprobadas: [], isElectiva: true },
      { id: "sis_99069", year: 5, semester: "1° Cuatrimestre", name: "Aprendizaje de Máquinas", weekly_hours: 0, total_hours: 0, estado: "pendiente", regulares: [], aprobadas: [], isElectiva: true },
      { id: "sis_99070", year: 5, semester: "1° Cuatrimestre", name: "Programación Avanzada", weekly_hours: 0, total_hours: 0, estado: "pendiente", regulares: [], aprobadas: [], isElectiva: true },
      { id: "sis_99071", year: 5, semester: "2° Cuatrimestre", name: "Taller de Programación Avanzada", weekly_hours: 6, total_hours: 0, estado: "pendiente", regulares: ["sis_19"], aprobadas: ["sis_13", "sis_14"], isElectiva: true },
      { id: "sis_99072", year: 5, semester: "2° Cuatrimestre", name: "Interoperabilidad", weekly_hours: 6, total_hours: 0, estado: "pendiente", regulares: ["sis_23", "sis_26"], aprobadas: ["sis_19", "sis_21"], isElectiva: true },
      { id: "sis_99073", year: 5, semester: "2° Cuatrimestre", name: "Formación de Emprendedores", weekly_hours: 0, total_hours: 0, estado: "pendiente", regulares: [], aprobadas: [], isElectiva: true, rendir: ["sis_19"] }
    ]
  },
  civil: {
    id: 'civil',
    name: 'Ingeniería Civil',
    shortName: 'Civil',
    requiredElectiveHours: 22,
    years: 6,
    icon: React.createElement(Building2, { className: "w-8 h-8" }),
    color: 'from-[#E8CFC3] to-[#D4856A]',
    curriculum: [
      { id: "civ_4", year: 1, semester: "Anual", name: "Ingeniería Civil I", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "utn_sdr", year: 1, semester: "Anual", name: "Sistemas de Representación", weekly_hours: 2, total_hours: 72, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "civ_8", year: 1, semester: "Anual", name: "Fundamentos de Informática", weekly_hours: 2, total_hours: 48, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "utn_am1", year: 1, semester: "1º Cuatrimestre", name: "Análisis Matemático I", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "utn_aga", year: 1, semester: "1º Cuatrimestre", name: "Álgebra y Geometría Analítica", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "utn_ing_soc", year: 1, semester: "1º Cuatrimestre", name: "Ingeniería y Sociedad", weekly_hours: 2, total_hours: 48, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "utn_qui_gen", year: 1, semester: "2º Cuatrimestre", name: "Química General", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "utn_fis1", year: 1, semester: "2º Cuatrimestre", name: "Física I", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "civ_11", year: 2, semester: "Anual", name: "Ingeniería Civil II", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: ["utn_ing_soc", "civ_4", "utn_sdr", "civ_8"], aprobadas: [] },
      { id: "utn_am2", year: 2, semester: "Anual", name: "Análisis Matemático II", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["utn_am1", "utn_aga"], aprobadas: [] },
      { id: "civ_12", year: 2, semester: "Anual", name: "Tecnología de los Materiales", weekly_hours: 4, total_hours: 96, estado: "pendiente", regulares: ["utn_am1", "utn_sdr", "utn_qui_gen", "utn_fis1"], aprobadas: [] },
      { id: "civ_10", year: 2, semester: "1º Cuatrimestre", name: "Estabilidad", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["utn_am1", "utn_aga", "utn_sdr", "utn_fis1", "civ_8"], aprobadas: [] },
      { id: "utn_fis2", year: 2, semester: "2º Cuatrimestre", name: "Física II", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["utn_am1", "utn_fis1"], aprobadas: [] },
      { id: "utn_prob", year: 2, semester: "2º Cuatrimestre", name: "Probabilidad y Estadística", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: ["utn_am1", "utn_aga"], aprobadas: [] },
      { id: "civ_15", year: 2, semester: "2º Cuatrimestre", name: "Inglés I (Materia cuatrimestral de cualquier cuatrimestre. Puede rendir libre).", weekly_hours: 2, total_hours: 48, estado: "pendiente", regulares: ["utn_ing_soc"], aprobadas: [] },
      { id: "civ_16", year: 3, semester: "Anual", name: "Resistencia de Materiales", weekly_hours: 4, total_hours: 96, estado: "pendiente", regulares: ["civ_10"], aprobadas: ["utn_am1", "utn_aga", "utn_fis1", "civ_8"] },
      { id: "civ_18", year: 3, semester: "Anual", name: "Tecnología de la Construcción", weekly_hours: 6, total_hours: 144, estado: "pendiente", regulares: ["civ_10", "civ_11", "civ_12", "civ_15"], aprobadas: ["utn_am1", "utn_aga", "civ_4", "utn_sdr", "utn_qui_gen", "utn_fis1", "civ_8"] },
      { id: "civ_20", year: 3, semester: "Anual", name: "Hidráulica General y Aplicada", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["utn_am2", "civ_10", "civ_11", "utn_fis2", "utn_prob"], aprobadas: ["utn_am1", "utn_aga", "utn_sdr", "utn_fis1", "civ_8"] },
      { id: "civ_17", year: 3, semester: "1º Cuatrimestre", name: "Tecnología del Hormigón", weekly_hours: 2, total_hours: 48, estado: "pendiente", regulares: ["civ_12", "utn_prob", "civ_15"], aprobadas: ["utn_am1", "utn_aga", "utn_qui_gen", "utn_fis1"] },
      { id: "civ_22", year: 3, semester: "1º Cuatrimestre", name: "Instalaciones Eléctricas Acústicas", weekly_hours: 2, total_hours: 48, estado: "pendiente", regulares: ["civ_11", "civ_12", "utn_fis2"], aprobadas: ["utn_am1", "utn_aga", "civ_4", "utn_sdr", "utn_qui_gen", "utn_fis1"] },
      { id: "civ_23", year: 3, semester: "1º Cuatrimestre", name: "Instalaciones Termomecánicas", weekly_hours: 2, total_hours: 48, estado: "pendiente", regulares: ["civ_11", "civ_12", "utn_fis2"], aprobadas: ["utn_am1", "utn_aga", "civ_4", "utn_sdr", "utn_qui_gen", "utn_fis1"] },
      { id: "civ_19", year: 3, semester: "2º Cuatrimestre", name: "Geotopografía", weekly_hours: 4, total_hours: 96, estado: "pendiente", regulares: ["utn_am2", "civ_11", "utn_fis2", "utn_prob"], aprobadas: ["utn_am1", "utn_aga", "civ_4", "utn_sdr", "utn_fis1"] },
      { id: "civ_21", year: 3, semester: "2º Cuatrimestre", name: "Cálculo Avanzado", weekly_hours: 2, total_hours: 48, estado: "pendiente", regulares: ["utn_am2", "civ_10", "civ_12", "utn_prob"], aprobadas: ["utn_am1", "utn_aga", "utn_sdr", "utn_fis1", "civ_8"] },
      { id: "utn_econo", year: 3, semester: "2º Cuatrimestre", name: "Economía", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: ["civ_11", "utn_prob", "civ_15"], aprobadas: ["utn_am1", "utn_aga", "utn_ing_soc", "civ_4", "civ_8"] },
      { id: "civ_25", year: 3, semester: "2º Cuatrimestre", name: "Inglés II (Materia cuatrimestral de cualquier cuatrimestre. Puede rendir libre).", weekly_hours: 2, total_hours: 48, estado: "pendiente", regulares: ["civ_15"], aprobadas: ["utn_ing_soc", "civ_4"] },
      { id: "civ_28", year: 4, semester: "Anual", name: "Diseño Arquitectónico, Planeamiento y Urbanismo", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["civ_18", "civ_19", "civ_22", "civ_23", "utn_econo", "civ_25"], aprobadas: ["civ_10", "civ_11", "civ_12", "civ_15"] },
      { id: "civ_31", year: 4, semester: "Anual", name: "Hidrología y Obras Hidráulicas", weekly_hours: 4, total_hours: 96, estado: "pendiente", regulares: ["civ_16", "civ_18", "civ_19", "civ_20", "utn_econo", "civ_25"], aprobadas: ["utn_am2", "civ_10", "civ_11", "civ_12", "utn_fis2", "utn_prob"] },
      { id: "civ_27", year: 4, semester: "1º Cuatrimestre", name: "Instalaciones Sanitarias y Gas", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: ["civ_18", "civ_19", "civ_20", "utn_econo"], aprobadas: ["utn_sdr", "utn_qui_gen", "utn_fis1", "civ_8", "civ_12"] },
      { id: "civ_29", year: 4, semester: "1º Cuatrimestre", name: "Análisis Estructural I", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["civ_16", "civ_17"], aprobadas: ["utn_am2", "civ_10", "civ_11", "utn_prob"] },
      { id: "civ_26", year: 4, semester: "2º Cuatrimestre", name: "Geotecnia", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["civ_16", "civ_17", "civ_18", "civ_19", "civ_20"], aprobadas: ["utn_am2", "civ_10", "civ_11", "civ_12", "utn_fis2", "utn_prob"] },
      { id: "civ_30", year: 4, semester: "2º Cuatrimestre", name: "Estructuras de Hormigón", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["civ_16", "civ_17", "civ_18", "civ_19", "civ_25"], aprobadas: ["utn_am2", "civ_10", "civ_11", "civ_12", "utn_fis2", "utn_prob"] },
      { id: "civ_32", year: 4, semester: "2º Cuatrimestre", name: "Ingeniería Legal", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: ["utn_am2", "civ_11", "utn_prob", "civ_15"], aprobadas: ["utn_am1", "utn_aga", "utn_ing_soc", "civ_4", "civ_8"] },
      { id: "civ_36", year: 5, semester: "Anual", name: "Organización y Conducción de Obras", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["civ_26", "civ_27", "civ_28", "civ_30", "civ_31"], aprobadas: ["civ_17", "civ_18", "civ_19", "civ_20", "civ_22", "civ_23", "utn_econo", "civ_25"] },
      { id: "civ_34", year: 5, semester: "1º Cuatrimestre", name: "Cimentaciones", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: ["civ_21", "civ_26", "civ_29", "civ_30", "civ_31"], aprobadas: ["civ_16", "civ_17", "civ_18", "civ_19", "civ_20"] },
      { id: "civ_35", year: 5, semester: "1º Cuatrimestre", name: "Ingeniería Sanitaria", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: ["civ_26", "civ_27", "civ_31"], aprobadas: ["civ_17", "civ_18", "civ_19", "civ_20", "civ_25"] },
      { id: "civ_37", year: 5, semester: "1º Cuatrimestre", name: "Vías de Comunicación I", weekly_hours: 4, total_hours: 96, estado: "pendiente", regulares: ["civ_17", "civ_18", "civ_19"], aprobadas: ["utn_am2", "civ_10", "civ_11", "civ_12", "utn_prob", "civ_15"] },
      { id: "civ_40", year: 5, semester: "1º Cuatrimestre", name: "Gestión Ambiental y Desarrollo Sustentable", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: ["civ_26", "civ_28", "civ_31", "civ_32"], aprobadas: ["civ_20", "utn_econo", "civ_25"] },
      { id: "civ_33", year: 5, semester: "2º Cuatrimestre", name: "Construcciones Metálicas y de Madera", weekly_hours: 4, total_hours: 96, estado: "pendiente", regulares: ["civ_21", "civ_29"], aprobadas: ["civ_16", "civ_17", "civ_18", "civ_19"] },
      { id: "civ_38", year: 5, semester: "2º Cuatrimestre", name: "Análisis Estructural II", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["civ_21", "civ_26", "civ_29", "civ_30", "civ_31"], aprobadas: ["civ_16", "civ_17", "civ_18", "civ_19", "civ_25"] },
      { id: "civ_39", year: 5, semester: "2º Cuatrimestre", name: "Vías de Comunicación II", weekly_hours: 4, total_hours: 96, estado: "pendiente", regulares: ["civ_26", "civ_30", "civ_31", "civ_32", "civ_37"], aprobadas: ["civ_16", "civ_17", "civ_18", "civ_19", "civ_20", "utn_econo"] },
      { id: "civ_41", year: 6, semester: "1º Cuatrimestre", name: "Proyecto Final", weekly_hours: 8, total_hours: 96, estado: "pendiente", regulares: ["civ_26", "civ_27", "civ_28", "civ_29", "civ_30", "civ_31", "civ_32"], aprobadas: ["civ_15", "civ_16", "civ_17", "civ_18", "civ_19", "civ_20", "civ_22", "civ_23", "utn_econo", "civ_25"] },
      { id: "civ_999", year: 6, semester: "Electiva", name: "Materias Electivas", weekly_hours: 22, total_hours: 264, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "civ_99001", year: 3, semester: "1° Cuatrimestre", name: "Geología Aplicada", weekly_hours: 0, total_hours: 0, estado: "pendiente", regulares: ["civ_12"], aprobadas: ["civ_4", "utn_qui_gen", "utn_am1"], isElectiva: true, rendir: ["civ_12"] },
      { id: "civ_99002", year: 4, semester: "1° Cuatrimestre", name: "Sustentabilidad del Recurso Hídrico", weekly_hours: 0, total_hours: 0, estado: "pendiente", regulares: ["civ_20", "civ_18"], aprobadas: ["civ_11"], isElectiva: true, rendir: ["civ_11", "civ_20", "civ_18"] },
      { id: "civ_99003", year: 4, semester: "2° Cuatrimestre", name: "Ferrocarriles", weekly_hours: 0, total_hours: 0, estado: "pendiente", regulares: ["civ_37", "civ_18"], aprobadas: ["civ_11", "civ_12"], isElectiva: true, rendir: ["civ_37", "civ_18"] },
      { id: "civ_99004", year: 4, semester: "2° Cuatrimestre", name: "Tránsito y Transporte", weekly_hours: 0, total_hours: 0, estado: "pendiente", regulares: ["civ_37"], aprobadas: ["utn_prob", "civ_11"], isElectiva: true, rendir: ["civ_37"] },
      { id: "civ_99005", year: 4, semester: "2° Cuatrimestre", name: "Prefabricación", weekly_hours: 0, total_hours: 0, estado: "pendiente", regulares: ["civ_17", "civ_16"], aprobadas: ["civ_18", "civ_12"], isElectiva: true, rendir: ["civ_17", "civ_16"] },
      { id: "civ_99006", year: 4, semester: "2° Cuatrimestre", name: "Diseño Estructural", weekly_hours: 0, total_hours: 0, estado: "pendiente", regulares: ["civ_16", "civ_18", "civ_29"], aprobadas: ["civ_10", "civ_11"], isElectiva: true, rendir: ["civ_16", "civ_29"] },
      { id: "civ_99007", year: 5, semester: "1° Cuatrimestre", name: "Gestión Ingenieril", weekly_hours: 0, total_hours: 0, estado: "pendiente", regulares: ["utn_econo", "civ_32"], aprobadas: ["civ_18"], isElectiva: true, rendir: ["utn_econo", "civ_32"] },
      { id: "civ_99008", year: 5, semester: "1° Cuatrimestre", name: "Dinámica de Estructuras", weekly_hours: 0, total_hours: 0, estado: "pendiente", regulares: ["civ_29", "civ_21"], aprobadas: ["utn_aga", "civ_16"], isElectiva: true, rendir: ["civ_29", "civ_21"] },
      { id: "civ_99009", year: 5, semester: "1° Cuatrimestre", name: "Análisis Estructural III", weekly_hours: 0, total_hours: 0, estado: "pendiente", regulares: ["civ_29", "civ_30"], aprobadas: ["civ_16", "civ_21"], isElectiva: true, rendir: ["civ_29", "civ_30"] },
      { id: "civ_99010", year: 5, semester: "1° Cuatrimestre", name: "Saneamiento y Medio Ambiente", weekly_hours: 0, total_hours: 0, estado: "pendiente", regulares: ["civ_31", "civ_32"], aprobadas: ["civ_11", "civ_20"], isElectiva: true, rendir: ["civ_31"] },
      { id: "civ_99011", year: 5, semester: "1° Cuatrimestre", name: "Vialidad Especial", weekly_hours: 0, total_hours: 0, estado: "pendiente", regulares: ["civ_37"], aprobadas: ["civ_18"], isElectiva: true, rendir: ["civ_37"] },
      { id: "civ_99012", year: 5, semester: "1° Cuatrimestre", name: "Caminos y Túneles de Montañas", weekly_hours: 0, total_hours: 0, estado: "pendiente", regulares: ["civ_37", "civ_31"], aprobadas: ["civ_17", "civ_19"], isElectiva: true, rendir: ["civ_37", "civ_31"] },
      { id: "civ_99013", year: 5, semester: "2° Cuatrimestre", name: "Obras Fluviales y Costeras", weekly_hours: 0, total_hours: 0, estado: "pendiente", regulares: ["civ_31"], aprobadas: ["civ_19", "civ_17", "civ_18"], isElectiva: true, rendir: ["civ_20", "civ_31"] },
      { id: "civ_99014", year: 5, semester: "2° Cuatrimestre", name: "Centrales y Máquinas Hidráulicas", weekly_hours: 0, total_hours: 0, estado: "pendiente", regulares: ["civ_20", "civ_22"], aprobadas: ["civ_19", "civ_16"], isElectiva: true, rendir: ["civ_31", "civ_22", "civ_20"] },
      { id: "civ_99015", year: 5, semester: "2° Cuatrimestre", name: "Puentes", weekly_hours: 0, total_hours: 0, estado: "pendiente", regulares: ["civ_26", "civ_30"], aprobadas: ["civ_17", "civ_16"], isElectiva: true, rendir: ["civ_26", "civ_30"] },
      { id: "civ_99016", year: 5, semester: "2° Cuatrimestre", name: "Diseño Sustentable de Edificios", weekly_hours: 0, total_hours: 0, estado: "pendiente", regulares: ["civ_28", "civ_32"], aprobadas: ["civ_18"], isElectiva: true, rendir: ["civ_28", "civ_32"] }
    ]
  },
  quimica: {
    id: 'quimica',
    name: 'Ingeniería Química',
    shortName: 'Química',
    requiredElectiveHours: 24,
    years: 5,
    icon: React.createElement(FlaskConical, { className: "w-8 h-8" }),
    color: 'from-[#F5E8E8] to-[#C28B8B]',
    curriculum: [
      { id: "qui_1", year: 1, semester: "Anual", name: "Introducción a la Ingeniería Química", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "utn_sdr", year: 1, semester: "Anual", name: "Sistemas de representación", weekly_hours: 2, total_hours: 48, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "utn_ing_soc", year: 1, semester: "1º Cuatrimestre", name: "Ingeniería y Sociedad", weekly_hours: 2, total_hours: 48, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "utn_aga", year: 1, semester: "1º Cuatrimestre", name: "Álgebra y Geometría Analítica", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "utn_am1", year: 1, semester: "1º Cuatrimestre", name: "Análisis Matemático I", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "utn_fis1", year: 1, semester: "2º Cuatrimestre", name: "Física I", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "qui_6", year: 1, semester: "2º Cuatrimestre", name: "Química", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "qui_9", year: 2, semester: "Anual", name: "Introducción a Equipos y Procesos", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: ["utn_am1", "qui_6"], aprobadas: [] },
      { id: "qui_14", year: 2, semester: "Anual", name: "Química Orgánica", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["qui_6"], aprobadas: [] },
      { id: "utn_prob", year: 2, semester: "1º Cuatrimestre", name: "Probabilidad y Estadística", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: ["utn_fis1", "utn_ing1"], aprobadas: [] },
      { id: "qui_11", year: 2, semester: "1º Cuatrimestre", name: "Química Inorgánica", weekly_hours: 4, total_hours: 96, estado: "pendiente", regulares: ["qui_6"], aprobadas: [] },
      { id: "utn_am2", year: 2, semester: "1º Cuatrimestre", name: "Análisis Matemático II", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["utn_am1", "utn_aga"], aprobadas: [] },
      { id: "utn_fis2", year: 2, semester: "2º Cuatrimestre", name: "Física II", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["utn_ing1", "utn_fis1"], aprobadas: [] },
      { id: "utn_legis", year: 2, semester: "2º Cuatrimestre", name: "Legislación", weekly_hours: 2, total_hours: 48, estado: "pendiente", regulares: ["utn_am1", "utn_aga"], aprobadas: [] },
      { id: "qui_8", year: 2, semester: "2º Cuatrimestre", name: "Fundamentos de Informática", weekly_hours: 2, total_hours: 48, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "qui_16", year: 2, semester: "2º Cuatrimestre", name: "Inglés I (Nota: Consultar en Bedelía de Básicas por cursado en 1º Cuatrimestre)", weekly_hours: 2, total_hours: 48, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "qui_17", year: 3, semester: "Anual", name: "Balances de Masa y Energía", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: ["qui_6", "utn_sdr", "qui_8", "qui_9", "utn_fis2"], aprobadas: ["utn_am1", "utn_fis1", "utn_ing1"] },
      { id: "qui_18", year: 3, semester: "1º Cuatrimestre", name: "Termodinámica", weekly_hours: 4, total_hours: 96, estado: "pendiente", regulares: ["qui_11", "utn_ing2", "utn_fis2"], aprobadas: ["utn_ing1", "qui_6"] },
      { id: "qui_19", year: 3, semester: "1º Cuatrimestre", name: "Matemática Superior Aplicada", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: ["utn_ing2"], aprobadas: ["utn_fis1", "utn_ing1"] },
      { id: "qui_23", year: 3, semester: "1º Cuatrimestre", name: "Química Analítica", weekly_hours: 4, total_hours: 96, estado: "pendiente", regulares: ["utn_fis2", "qui_11", "qui_14"], aprobadas: ["utn_aga", "qui_6"] },
      { id: "qui_24", year: 3, semester: "1º Cuatrimestre", name: "Microbiología y Química Biológica", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: ["qui_11", "qui_14"], aprobadas: ["qui_6"] },
      { id: "qui_20", year: 3, semester: "2º Cuatrimestre", name: "Ciencia de los Materiales", weekly_hours: 2, total_hours: 48, estado: "pendiente", regulares: ["qui_9", "qui_11", "qui_14"], aprobadas: ["utn_am1", "qui_6"] },
      { id: "qui_21", year: 3, semester: "2º Cuatrimestre", name: "Fisicoquímica", weekly_hours: 4, total_hours: 96, estado: "pendiente", regulares: ["qui_9", "utn_ing2", "utn_fis2"], aprobadas: ["utn_fis1", "utn_ing1", "qui_6"] },
      { id: "qui_22", year: 3, semester: "2º Cuatrimestre", name: "Fenómenos de Transporte", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["qui_9", "utn_ing2", "utn_fis2"], aprobadas: ["utn_fis1", "utn_ing1", "qui_6"] },
      { id: "qui_25", year: 3, semester: "2º Cuatrimestre", name: "Química Analítica Aplicada", weekly_hours: 2, total_hours: 48, estado: "pendiente", regulares: ["qui_9", "qui_11", "utn_fis2", "qui_16"], aprobadas: ["utn_am1", "utn_aga", "qui_6", "qui_16"] },
      { id: "qui_26", year: 3, semester: "2º Cuatrimestre", name: "Inglés II (Nota: Se cursará a partir del 1º cuatrimestre del 2024)", weekly_hours: 2, total_hours: 48, estado: "pendiente", regulares: ["qui_16"], aprobadas: [] },
      { id: "qui_27", year: 4, semester: "Anual", name: "Diseño, simulación, optimización y seguridad de procesos", weekly_hours: 4, total_hours: 96, estado: "pendiente", regulares: ["qui_17", "qui_19"], aprobadas: ["utn_sdr", "qui_8", "qui_9", "utn_ing2", "qui_26"] },
      { id: "qui_28", year: 4, semester: "Anual", name: "Operaciones Unitarias I", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["qui_17", "qui_18", "qui_22"], aprobadas: ["qui_9", "utn_ing2", "utn_fis2"] },
      { id: "qui_32", year: 4, semester: "Anual", name: "Ingeniería de las Reacciones Químicas", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["qui_17", "qui_18", "qui_21", "qui_22"], aprobadas: ["qui_11", "utn_ing2", "qui_14"] },
      { id: "qui_29", year: 4, semester: "1º Cuatrimestre", name: "Tecnología de la Energía Térmica", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["qui_17", "qui_18", "qui_21", "qui_22"], aprobadas: ["qui_9", "utn_ing2", "utn_fis2"] },
      { id: "utn_econo", year: 4, semester: "1º Cuatrimestre", name: "Economía", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: ["qui_9"], aprobadas: ["utn_aga", "utn_fis1"] },
      { id: "qui_33", year: 4, semester: "1º Cuatrimestre", name: "Calidad y Control Estadístico de Procesos", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: ["utn_fis2"], aprobadas: ["utn_ing1"] },
      { id: "qui_31", year: 4, semester: "2º Cuatrimestre", name: "Operaciones Unitarias II", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["qui_18", "qui_21", "qui_22"], aprobadas: ["qui_9", "utn_ing2", "utn_fis2", "qui_14"] },
      { id: "qui_34", year: 4, semester: "2º Cuatrimestre", name: "Organización Industrial", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: ["utn_fis2"], aprobadas: ["utn_aga", "qui_9", "utn_legis"] },
      { id: "qui_35", year: 5, semester: "Anual", name: "Control Automático de Procesos", weekly_hours: 4, total_hours: 96, estado: "pendiente", regulares: ["qui_27", "qui_31"], aprobadas: ["qui_17", "qui_19", "qui_23"] },
      { id: "qui_41", year: 5, semester: "Anual", name: "Proyecto Final", note: "Para rendir se requiere tener aprobadas todas", weekly_hours: 4, total_hours: 96, estado: "pendiente", regulares: ["qui_27", "qui_28", "qui_29", "qui_31", "qui_32", "qui_34"], aprobadas: ["qui_17", "qui_21", "qui_22", "qui_25", "utn_econo"] },
      { id: "qui_37", year: 5, semester: "Anual", name: "Ingeniería Ambiental", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: ["qui_25", "qui_28", "qui_31", "qui_32"], aprobadas: ["utn_legis", "qui_17", "qui_23"] },
      { id: "qui_36", year: 5, semester: "1º Cuatrimestre", name: "Mecánica Industrial", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: ["qui_9", "qui_21"], aprobadas: ["utn_fis1", "qui_11", "qui_20"] },
      { id: "qui_38", year: 5, semester: "2º Cuatrimestre", name: "Procesos Biotecnológicos", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: ["qui_17", "qui_21", "qui_22", "qui_24"], aprobadas: ["qui_9", "qui_11", "qui_14"] },
      { id: "qui_39", year: 5, semester: "2º Cuatrimestre", name: "Higiene y Seguridad en el Trabajo", weekly_hours: 2, total_hours: 48, estado: "pendiente", regulares: ["qui_11", "qui_14", "qui_17"], aprobadas: ["qui_9"] },
      { id: "qui_40", year: 5, semester: "2º Cuatrimestre", name: "Máquinas e Instalaciones Eléctricas", weekly_hours: 2, total_hours: 48, estado: "pendiente", regulares: ["qui_9", "utn_fis2"], aprobadas: ["qui_28"] },
      { id: "qui_998", year: 5, semester: "Electiva", name: "Materias Electivas", weekly_hours: 12, total_hours: 288, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "qui_99041", year: 3, semester: "2° Cuatrimestre", name: "Epistemología", weekly_hours: 5, total_hours: 0, estado: "pendiente", regulares: [], aprobadas: [], isElectiva: true },
      { id: "qui_99042", year: 3, semester: "2° Cuatrimestre", name: "Metodología de la Investigación", weekly_hours: 6, total_hours: 0, estado: "pendiente", regulares: [], aprobadas: [], isElectiva: true },
      { id: "qui_99043", year: 4, semester: "1° Cuatrimestre", name: "Utilitarios de Computación", weekly_hours: 4, total_hours: 0, estado: "pendiente", regulares: ["qui_21", "qui_22"], aprobadas: ["qui_11", "qui_18"], isElectiva: true, rendir: ["qui_21", "qui_22"] },
      { id: "qui_99044", year: 4, semester: "2° Cuatrimestre", name: "Gestión de RRHH", weekly_hours: 6, total_hours: 0, estado: "pendiente", regulares: ["qui_17", "qui_18", "qui_20", "qui_21", "qui_22", "qui_23", "qui_24", "qui_26"], aprobadas: ["qui_8", "qui_9", "utn_prob", "qui_11", "utn_aga", "utn_aga", "qui_14", "utn_legis", "qui_16"], isElectiva: true, rendir: ["qui_17", "qui_18", "qui_20", "qui_21", "qui_22", "qui_23", "qui_24", "qui_26"] },
      { id: "qui_99045", year: 4, semester: "2° Cuatrimestre", name: "Análisis del Ciclo de Vida (ACV)", weekly_hours: 4, total_hours: 0, estado: "pendiente", regulares: ["qui_17", "qui_22"], aprobadas: ["qui_9"], isElectiva: true, rendir: ["qui_17", "qui_22"] },
      { id: "qui_99046", year: 5, semester: "Anual", name: "Instalaciones de Maq. térmicas y fluidodinámicas", weekly_hours: 8, total_hours: 0, estado: "pendiente", regulares: ["qui_28", "qui_29", "qui_31"], aprobadas: ["qui_18"], isElectiva: true, rendir: ["qui_28", "qui_29", "qui_31"] },
      { id: "qui_99047", year: 5, semester: "Anual", name: "Industrialización de Hidrocarburos", weekly_hours: 6, total_hours: 0, estado: "pendiente", regulares: ["qui_28", "qui_29", "qui_31", "qui_32"], aprobadas: ["qui_18", "qui_21", "qui_22"], isElectiva: true, rendir: ["qui_28", "qui_29", "qui_31", "qui_32"] },
      { id: "qui_99048", year: 5, semester: "1° Cuatrimestre", name: "Gestión Empresarial I", weekly_hours: 4, total_hours: 0, estado: "pendiente", regulares: ["utn_econo", "qui_33"], aprobadas: ["utn_aga", "utn_aga"], isElectiva: true, rendir: ["utn_econo", "qui_33"] },
      { id: "qui_99049", year: 5, semester: "1° Cuatrimestre", name: "Bioquímica de los Alimentos", weekly_hours: 6, total_hours: 0, estado: "pendiente", regulares: ["qui_21", "qui_24"], aprobadas: ["qui_11", "qui_14"], isElectiva: true, rendir: ["qui_21", "qui_24"] },
      { id: "qui_99050", year: 5, semester: "1° Cuatrimestre", name: "Ind. Alimentarias", weekly_hours: 6, total_hours: 0, estado: "pendiente", regulares: ["qui_20", "qui_28", "qui_29"], aprobadas: [], isElectiva: true, rendir: ["qui_20", "qui_28", "qui_29"] },
      { id: "qui_99051", year: 5, semester: "1° Cuatrimestre", name: "Ind. de Base Extractiva - Ext., Fracc., Ref.", weekly_hours: 6, total_hours: 0, estado: "pendiente", regulares: ["qui_28", "qui_31", "qui_32"], aprobadas: ["qui_28"], isElectiva: true, rendir: ["qui_28", "qui_31", "qui_32"] },
      { id: "qui_99052", year: 5, semester: "2° Cuatrimestre", name: "Evaluación de Impacto Ambiental", weekly_hours: 4, total_hours: 0, estado: "pendiente", regulares: ["qui_22", "qui_23"], aprobadas: ["qui_6"], isElectiva: true, rendir: ["qui_22", "qui_23"] },
      { id: "qui_99053", year: 5, semester: "2° Cuatrimestre", name: "Gestión Empresarial II", weekly_hours: 4, total_hours: 0, estado: "pendiente", regulares: ["qui_33"], aprobadas: ["utn_aga", "utn_aga", "qui_21"], isElectiva: true, rendir: ["qui_33"] },
      { id: "qui_99054", year: 5, semester: "2° Cuatrimestre", name: "Ing. Industrial de Recursos Naturales Regionales", weekly_hours: 6, total_hours: 0, estado: "pendiente", regulares: ["qui_17", "qui_20", "qui_28", "qui_29"], aprobadas: [], isElectiva: true, rendir: ["qui_17", "qui_20", "qui_28", "qui_29"] },
      { id: "qui_99055", year: 5, semester: "2° Cuatrimestre", name: "Formación de Emprendedores", weekly_hours: 4, total_hours: 0, estado: "pendiente", regulares: ["qui_19"], aprobadas: [], isElectiva: true, rendir: ["qui_19"] }
    ]
  },
  electronica: {
    id: 'electronica',
    name: 'Ingeniería Electrónica',
    shortName: 'Electrónica',
    requiredElectiveHours: 6,
    years: 6,
    icon: React.createElement(Cpu, { className: "w-8 h-8" }),
    color: 'from-[#FFF0E5] to-[#E8A87C]',
    curriculum: [
      { id: "ele_1", year: 1, semester: "Anual", name: "Informática I", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "utn_aga", year: 1, semester: "1º Cuatrimestre", name: "Álgebra y Geometría Analítica", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "utn_am1", year: 1, semester: "1º Cuatrimestre", name: "Análisis Matemático I", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "utn_ing_soc", year: 1, semester: "1º Cuatrimestre", name: "Ingeniería y Sociedad", weekly_hours: 2, total_hours: 48, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "utn_am2", year: 1, semester: "2º Cuatrimestre", name: "Análisis Matemático II", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["utn_aga", "utn_am1"], aprobadas: [] },
      { id: "utn_fis1", year: 1, semester: "2º Cuatrimestre", name: "Física I", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "ele_7", year: 1, semester: "2º Cuatrimestre", name: "Diseño asistido por computadora", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "ele_8", year: 2, semester: "Anual", name: "Informática II", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["utn_am1", "utn_aga", "utn_fis1"], aprobadas: [] },
      { id: "ele_9", year: 2, semester: "Anual", name: "Análisis de Señales y Sistemas", weekly_hours: 6, total_hours: 144, estado: "pendiente", regulares: ["utn_am2"], aprobadas: ["utn_aga", "utn_am1"] },
      { id: "utn_qui_gen", year: 2, semester: "1º Cuatrimestre", name: "Química General", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "utn_fis2", year: 2, semester: "1º Cuatrimestre", name: "Física II", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["utn_am1", "utn_fis1"], aprobadas: [] },
      { id: "utn_prob", year: 2, semester: "2º Cuatrimestre", name: "Probabilidad y Estadística", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: ["utn_aga", "utn_am1"], aprobadas: [] },
      { id: "ele_13", year: 2, semester: "2º Cuatrimestre", name: "Física Electrónica", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["utn_fis2"], aprobadas: ["utn_aga", "utn_am1", "utn_fis1"] },
      { id: "ele_14", year: 2, semester: "2º Cuatrimestre", name: "Inglés I (Nota: Consultar en Bedelía de Básicas por cursado en 1º Cuatrimestre)", weekly_hours: 2, total_hours: 48, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "ele_15", year: 3, semester: "Anual", name: "Teoría de los Circuitos I", weekly_hours: 6, total_hours: 144, estado: "pendiente", regulares: ["utn_am2", "utn_fis2"], aprobadas: ["utn_am1", "utn_fis1"] },
      { id: "ele_16", year: 3, semester: "Anual", name: "Técnicas Digitales I", weekly_hours: 4, total_hours: 96, estado: "pendiente", regulares: ["ele_1"], aprobadas: ["utn_aga"] },
      { id: "ele_17", year: 3, semester: "1º Cuatrimestre", name: "Dispositivos Electrónicos", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["ele_1", "utn_am1", "utn_qui_gen"], aprobadas: [] },
      { id: "utn_legis", year: 3, semester: "1º Cuatrimestre", name: "Legislación", weekly_hours: 2, total_hours: 48, estado: "pendiente", regulares: ["ele_8"], aprobadas: ["utn_ing_soc"] },
      { id: "ele_21", year: 3, semester: "1º Cuatrimestre", name: "Inglés II (Nota: Se cursará a partir del 1º cuatrimestre del 2024)", weekly_hours: 2, total_hours: 48, estado: "pendiente", regulares: [], aprobadas: ["ele_14"] },
      { id: "ele_19", year: 3, semester: "2º Cuatrimestre", name: "Electrónica Aplicada I", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["utn_qui_gen", "utn_fis2"], aprobadas: ["ele_1", "utn_am1", "utn_fis1"] },
      { id: "ele_20", year: 3, semester: "2º Cuatrimestre", name: "Medios de Enlace", weekly_hours: 4, total_hours: 96, estado: "pendiente", regulares: ["utn_am2", "utn_fis2"], aprobadas: ["utn_aga", "utn_am1", "utn_fis1"] },
      { id: "ele_22", year: 4, semester: "Anual", name: "Técnicas Digitales II", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["ele_8", "ele_16", "ele_19"], aprobadas: ["utn_qui_gen", "utn_fis2"] },
      { id: "ele_23", year: 4, semester: "Anual", name: "Medidas Electrónicas I", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["ele_9", "ele_15", "ele_16", "ele_19"], aprobadas: ["utn_am2", "utn_qui_gen", "utn_fis2"] },
      { id: "ele_24", year: 4, semester: "Anual", name: "Teoría de los Circuitos II", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["ele_9", "ele_15"], aprobadas: ["utn_am2", "utn_fis2"] },
      { id: "ele_25", year: 4, semester: "Anual", name: "Máquinas e Instalaciones Eléctricas", weekly_hours: 4, total_hours: 96, estado: "pendiente", regulares: ["ele_9", "ele_15"], aprobadas: ["utn_am2", "utn_fis2"] },
      { id: "ele_26", year: 4, semester: "Anual", name: "Sistemas de Comunicaciones", weekly_hours: 4, total_hours: 96, estado: "pendiente", regulares: ["ele_9", "utn_prob", "ele_19", "ele_20"], aprobadas: ["utn_am2", "utn_fis2"] },
      { id: "ele_27", year: 4, semester: "Anual", name: "Electrónica Aplicada II", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["ele_9", "ele_13", "ele_15", "ele_17", "ele_19"], aprobadas: ["utn_am2", "utn_fis2", "ele_14"] },
      { id: "ele_28", year: 4, semester: "Anual", name: "Seguridad, Higiene y Medio Ambiente", weekly_hours: 2, total_hours: 48, estado: "pendiente", regulares: [], aprobadas: ["utn_ing_soc", "utn_qui_gen"] },
      { id: "ele_29", year: 5, semester: "Anual", name: "Técnicas Digitales III", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["ele_22"], aprobadas: ["ele_8", "ele_16", "ele_19"] },
      { id: "ele_30", year: 5, semester: "Anual", name: "Medidas Electrónicas II", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["ele_22", "ele_23", "ele_26", "ele_27"], aprobadas: ["ele_7", "ele_13", "ele_15", "ele_16", "ele_19", "ele_21"] },
      { id: "ele_31", year: 5, semester: "Anual", name: "Sistemas de Control", weekly_hours: 4, total_hours: 96, estado: "pendiente", regulares: ["ele_24", "ele_25"], aprobadas: ["ele_13", "ele_15"] },
      { id: "ele_32", year: 5, semester: "Anual", name: "Electrónica Aplicada III", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["ele_24", "ele_26", "ele_27"], aprobadas: ["ele_13", "ele_15", "ele_19"] },
      { id: "ele_33", year: 5, semester: "Anual", name: "Tecnología Electrónica", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["ele_23"], aprobadas: ["ele_13", "ele_16", "ele_19"] },
      { id: "ele_34", year: 5, semester: "Anual", name: "Electrónica de Potencia", weekly_hours: 4, total_hours: 96, estado: "pendiente", regulares: ["ele_23", "ele_25", "ele_27"], aprobadas: ["ele_13", "ele_16", "ele_19"] },
      { id: "ele_35", year: 5, semester: "Anual", name: "Organización Industrial", weekly_hours: 2, total_hours: 48, estado: "pendiente", regulares: ["utn_legis"], aprobadas: [] },
      { id: "utn_econo", year: 6, semester: "1º Cuatrimestre", name: "Economía", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: ["ele_8"], aprobadas: ["utn_ing_soc"] },
      { id: "ele_37", year: 6, semester: "1º Cuatrimestre", name: "Proyecto Final", note: "Para rendir se requiere tener aprobadas todas", weekly_hours: 4, total_hours: 96, estado: "pendiente", regulares: ["ele_29", "ele_30", "ele_32"], aprobadas: ["ele_22", "ele_23", "ele_25", "ele_27"] },
      { id: "ele_997", year: 6, semester: "Electiva", name: "Materias Electivas", weekly_hours: 8, total_hours: 192, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "ele_99021", year: 5, semester: "1° Cuatrimestre", name: "Redes de Datos", weekly_hours: 0, total_hours: 6, estado: "pendiente", regulares: [], aprobadas: [], isElectiva: true, docente: "Dr. Ing. Pérez Santiago", horario: "17:30" },
      { id: "ele_99022", year: 5, semester: "1° Cuatrimestre", name: "Electrónica Industrial", weekly_hours: 0, total_hours: 6, estado: "pendiente", regulares: [], aprobadas: [], isElectiva: true, docente: "Ing. Allub Claudio", horario: "17:30" },
      { id: "ele_99023", year: 5, semester: "1° Cuatrimestre", name: "Sistemas de Comunicaciones II", weekly_hours: 0, total_hours: 6, estado: "pendiente", regulares: [], aprobadas: [], isElectiva: true, docente: "Ing. Alejandro Correa", horario: "18:10" },
      { id: "ele_99024", year: 5, semester: "1° Cuatrimestre", name: "Bioelectrónica", weekly_hours: 0, total_hours: 6, estado: "pendiente", regulares: [], aprobadas: [], isElectiva: true, docente: "Ing. Lombardo Germán", horario: "18:20" },
      { id: "ele_99025", year: 5, semester: "1° Cuatrimestre", name: "Introducción a los Sist. de Gestión Gerencial", weekly_hours: 0, total_hours: 4, estado: "pendiente", regulares: [], aprobadas: [], isElectiva: true, docente: "Dr. Ing. Anzoise Esteban", horario: "18:30" },
      { id: "ele_99026", year: 5, semester: "1° Cuatrimestre", name: "Sistemas de TV", weekly_hours: 0, total_hours: 6, estado: "pendiente", regulares: [], aprobadas: [], isElectiva: true, docente: "Ing. Boschi Cesar", horario: "18:50" },
      { id: "ele_99027", year: 5, semester: "1° Cuatrimestre", name: "Antenas y Propagación Electromagnética", weekly_hours: 0, total_hours: 6, estado: "pendiente", regulares: [], aprobadas: [], isElectiva: true, docente: "Ing. Wiens Martín", horario: "19:30" },
      { id: "ele_99028", year: 5, semester: "1° Cuatrimestre", name: "Centro de Datos: Diseño y Administración", weekly_hours: 0, total_hours: 6, estado: "pendiente", regulares: [], aprobadas: [], isElectiva: true, docente: "Ing. Abraham Jorge", horario: "20:30" },
      { id: "ele_99029", year: 5, semester: "1° Cuatrimestre", name: "Sistemas de Comunicaciones III", weekly_hours: 0, total_hours: 0, estado: "pendiente", regulares: [], aprobadas: [], isElectiva: true, docente: "Colombo, Humberto", horario: "21:15" },
      { id: "ele_99030", year: 5, semester: "1° Cuatrimestre", name: "Protecciones Digitales y Telecontrol", weekly_hours: 0, total_hours: 0, estado: "pendiente", regulares: [], aprobadas: [], isElectiva: true, docente: "Tobar, Sebastián", horario: "20:00" },
      { id: "ele_99031", year: 5, semester: "2° Cuatrimestre", name: "Redes de Comunicaciones Móviles", weekly_hours: 0, total_hours: 6, estado: "pendiente", regulares: [], aprobadas: [], isElectiva: true, docente: "Ing. Manzur Nestor", horario: "17:20" },
      { id: "ele_99032", year: 5, semester: "2° Cuatrimestre", name: "Evaluación e Innovación de Tecnología desde la perspectiva CTS", weekly_hours: 0, total_hours: 4, estado: "pendiente", regulares: [], aprobadas: [], isElectiva: true, docente: "Dr. Ing. Moralejo Raul", horario: "17:50" },
      { id: "ele_99033", year: 5, semester: "2° Cuatrimestre", name: "Formación de Emprendedores", weekly_hours: 0, total_hours: 4, estado: "pendiente", regulares: [], aprobadas: [], isElectiva: true, docente: "Dr. Ing. Anzoise Esteban", horario: "18:40", rendir: ["ele_19"] },
      { id: "ele_99034", year: 5, semester: "2° Cuatrimestre", name: "Sistemas de Sonido", weekly_hours: 0, total_hours: 6, estado: "pendiente", regulares: [], aprobadas: [], isElectiva: true, docente: "Ing. Boschi Cesar", horario: "19:10" },
      { id: "ele_99035", year: 5, semester: "2° Cuatrimestre", name: "Robótica", weekly_hours: 0, total_hours: 6, estado: "pendiente", regulares: [], aprobadas: [], isElectiva: true, docente: "Dr. Ing. Lannutti Esteban", horario: "19:20" },
      { id: "ele_99036", year: 5, semester: "2° Cuatrimestre", name: "Electrónica Automotriz", weekly_hours: 0, total_hours: 6, estado: "pendiente", regulares: [], aprobadas: [], isElectiva: true, docente: "Ing. Torres Dante", horario: "19:40" },
      { id: "ele_99037", year: 5, semester: "2° Cuatrimestre", name: "Control de Procesos", weekly_hours: 0, total_hours: 6, estado: "pendiente", regulares: [], aprobadas: [], isElectiva: true, docente: "Ing. Mocayar Nelson", horario: "20:20" },
      { id: "ele_99038", year: 5, semester: "2° Cuatrimestre", name: "Teleinformática en I o T", weekly_hours: 0, total_hours: 0, estado: "pendiente", regulares: [], aprobadas: [], isElectiva: true, docente: "Mercado Gustavo", horario: "19:00" },
      { id: "ele_99039", year: 5, semester: "2° Cuatrimestre", name: "Interoperabilidad", weekly_hours: 0, total_hours: 0, estado: "pendiente", regulares: [], aprobadas: [], isElectiva: true, docente: "Diaz Bruno", horario: "19:00" },
      { id: "ele_99040", year: 5, semester: "2° Cuatrimestre", name: "Dis. y Admin. de Centro de Datos", weekly_hours: 0, total_hours: 0, estado: "pendiente", regulares: [], aprobadas: [], isElectiva: true, docente: "Ing. Abraham Jorge", horario: "16:45" }
    ]
  },
  electromecanica: {
    id: 'electromecanica',
    name: 'Ingeniería Electromecánica',
    shortName: 'Electromecánica',
    requiredElectiveHours: 10,
    years: 5,
    icon: React.createElement(Zap, { className: "w-8 h-8" }),
    color: 'from-[#EFEBF5] to-[#B4A7D6]',
    curriculum: [
      { id: "elc_1", year: 1, semester: "Anual", name: "Ingeniería Electromecánica I", weekly_hours: 2, total_hours: 48, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "utn_am1", year: 1, semester: "1º Cuatrimestre", name: "Análisis Matemático I", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "utn_aga", year: 1, semester: "1º Cuatrimestre", name: "Álgebra y Geometría Analítica", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "utn_sdr", year: 1, semester: "1º Cuatrimestre", name: "Sistemas de Representación", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "utn_qui_gen", year: 1, semester: "2º Cuatrimestre", name: "Química General", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "utn_fis1", year: 1, semester: "2º Cuatrimestre", name: "Física I", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "elc_7", year: 1, semester: "2º Cuatrimestre", name: "Representación Gráfica", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "utn_ing_soc", year: 1, semester: "2º Cuatrimestre", name: "Ingeniería y Sociedad", weekly_hours: 2, total_hours: 48, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "elc_9", year: 2, semester: "Anual", name: "Ingeniería Electromecánica II", weekly_hours: 2, total_hours: 48, estado: "pendiente", regulares: ["elc_1", "utn_am1", "utn_aga"], aprobadas: [] },
      { id: "elc_10", year: 2, semester: "Anual", name: "Estabilidad", weekly_hours: 6, total_hours: 144, estado: "pendiente", regulares: ["utn_am1", "utn_aga", "utn_fis1"], aprobadas: [] },
      { id: "elc_11", year: 2, semester: "Anual", name: "Conocimiento de Materiales", weekly_hours: 4, total_hours: 96, estado: "pendiente", regulares: ["utn_qui_gen"], aprobadas: [] },
      { id: "utn_am2", year: 2, semester: "1º Cuatrimestre", name: "Análisis Matemático II", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["utn_am1", "utn_aga"], aprobadas: [] },
      { id: "utn_fis2", year: 2, semester: "1º Cuatrimestre", name: "Física II", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["utn_am1", "utn_fis1"], aprobadas: [] },
      { id: "utn_prob", year: 2, semester: "2º Cuatrimestre", name: "Probabilidad y Estadística", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: ["utn_am1", "utn_aga"], aprobadas: [] },
      { id: "elc_15", year: 2, semester: "2º Cuatrimestre", name: "Programación en Computación", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: ["utn_am1", "utn_aga"], aprobadas: [] },
      { id: "utn_ing1", year: 2, semester: "2º Cuatrimestre", name: "Inglés I", weekly_hours: 2, total_hours: 48, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "elc_16", year: 3, semester: "Anual", name: "Ingeniería Electromecánica III", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: ["elc_9", "utn_am2", "utn_fis2"], aprobadas: ["elc_1", "utn_am1", "utn_aga", "utn_fis1"] },
      { id: "elc_17", year: 3, semester: "Anual", name: "Mecánica y Mecanismos", weekly_hours: 4, total_hours: 96, estado: "pendiente", regulares: ["elc_7", "elc_10", "utn_am2"], aprobadas: ["utn_am1", "utn_aga", "utn_sdr", "utn_fis1"] },
      { id: "elc_18", year: 3, semester: "Anual", name: "Electrotecnia", weekly_hours: 6, total_hours: 144, estado: "pendiente", regulares: ["utn_am2", "utn_fis2"], aprobadas: ["utn_am1", "utn_aga", "utn_fis1"] },
      { id: "elc_19", year: 3, semester: "Anual", name: "Tecnología Mecánica", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["elc_11", "utn_fis2"], aprobadas: ["utn_am1", "utn_qui_gen", "utn_fis1", "elc_7"] },
      { id: "elc_20", year: 3, semester: "1º Cuatrimestre", name: "Termodinámica Técnica", weekly_hours: 4, total_hours: 96, estado: "pendiente", regulares: ["utn_fis2"], aprobadas: ["utn_am1", "utn_fis1"] },
      { id: "elc_21", year: 3, semester: "1º Cuatrimestre", name: "Matemática para Ing. Electromecánica", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: ["utn_am1", "utn_fis1"], aprobadas: ["utn_am1", "utn_aga"] },
      { id: "elc_23", year: 3, semester: "2º Cuatrimestre", name: "Higiene y Seguridad Industrial", weekly_hours: 2, total_hours: 48, estado: "pendiente", regulares: ["utn_fis2"], aprobadas: ["utn_am1", "utn_fis1"] },
      { id: "utn_ing2", year: 3, semester: "2º Cuatrimestre", name: "Inglés II", weekly_hours: 2, total_hours: 48, estado: "pendiente", regulares: ["utn_fis2"], aprobadas: ["utn_am1", "utn_qui_gen", "utn_fis1", "utn_ing_soc"] },
      { id: "elc_24", year: 4, semester: "Anual", name: "Elementos de Máquinas", weekly_hours: 6, total_hours: 144, estado: "pendiente", regulares: ["utn_fis2", "elc_16", "elc_17", "elc_19"], aprobadas: ["elc_9", "elc_10", "elc_11", "utn_am2", "utn_fis2", "elc_15", "utn_ing1"] },
      { id: "elc_25", year: 4, semester: "Anual", name: "Mecánica de los Fluidos y Máquinas Fluidodinámicas", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["utn_fis2", "elc_17", "elc_20", "elc_21"], aprobadas: ["elc_10", "utn_am2", "elc_15"] },
      { id: "elc_26", year: 4, semester: "Anual", name: "Máquinas Térmicas", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["elc_20", "elc_21"], aprobadas: ["utn_fis2"] },
      { id: "elc_27", year: 4, semester: "Anual", name: "Máquinas Eléctricas", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["elc_18", "elc_21"], aprobadas: ["utn_am2", "utn_fis2"] },
      { id: "elc_28", year: 4, semester: "1º Cuatrimestre", name: "Mediciones Eléctricas", weekly_hours: 4, total_hours: 96, estado: "pendiente", regulares: ["elc_18", "elc_21"], aprobadas: ["utn_am2", "utn_fis2"] },
      { id: "utn_legis", year: 4, semester: "1º Cuatrimestre", name: "Legislación", weekly_hours: 2, total_hours: 48, estado: "pendiente", regulares: ["elc_9"], aprobadas: ["utn_ing_soc"] },
      { id: "elc_30", year: 4, semester: "2º Cuatrimestre", name: "Electrónica Industrial", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: ["elc_18"], aprobadas: ["utn_am2", "utn_fis2"] },
      { id: "utn_econo", year: 4, semester: "2º Cuatrimestre", name: "Economía", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: ["elc_9"], aprobadas: ["utn_ing_soc"] },
      { id: "elc_33", year: 5, semester: "Anual", name: "Redes de Distribución e Instalaciones Eléctricas", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["elc_27", "elc_28"], aprobadas: ["elc_18", "elc_21"] },
      { id: "elc_34", year: 5, semester: "Anual", name: "Máquinas y Equipos de Transporte", weekly_hours: 2, total_hours: 48, estado: "pendiente", regulares: ["elc_24", "elc_25", "elc_30"], aprobadas: ["elc_16", "elc_19", "elc_21", "utn_ing1", "elc_23"] },
      { id: "elc_35", year: 5, semester: "Anual", name: "Gestión y Mantenimiento Electromecánico", weekly_hours: 2, total_hours: 48, estado: "pendiente", regulares: ["elc_25", "elc_27", "elc_30"], aprobadas: ["elc_16", "elc_17", "elc_18", "elc_19", "elc_21", "elc_23"] },
      { id: "elc_36", year: 5, semester: "1º Cuatrimestre", name: "Instalaciones Térmicas y Mecánicas", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: ["elc_25", "elc_26"], aprobadas: ["elc_17", "elc_20", "elc_21"] },
      { id: "elc_37", year: 5, semester: "1º Cuatrimestre", name: "Automatización y Control Industrial", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: ["elc_21", "elc_24", "elc_25", "elc_27", "elc_30"], aprobadas: ["elc_17", "elc_18", "elc_20", "elc_23"] },
      { id: "elc_38", year: 5, semester: "2º Cuatrimestre", name: "Centrales y Sistemas de Transmisión", weekly_hours: 5, total_hours: 120, estado: "pendiente", regulares: ["elc_25", "elc_27", "elc_28", "elc_30"], aprobadas: ["elc_17", "elc_18", "elc_20", "elc_21"] },
      { id: "elc_39", year: 5, semester: "2º Cuatrimestre", name: "Organización Industrial", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: ["elc_26", "utn_econo"], aprobadas: ["elc_9", "utn_prob"] },
      { id: "elc_41", year: 5, semester: "2º Cuatrimestre", name: "Oleohidráulica y Neumática", weekly_hours: 2, total_hours: 48, estado: "pendiente", regulares: ["elc_25"], aprobadas: ["utn_fis2", "elc_17", "elc_20"] },
      { id: "elc_40", year: 5, semester: "2º Cuatrimestre", name: "Proyecto Final", weekly_hours: 3, total_hours: 72, estado: "pendiente", regulares: ["elc_25", "elc_28", "elc_30", "utn_ing2"], aprobadas: ["elc_16", "elc_17", "elc_18", "elc_19", "elc_20", "elc_21", "elc_23"] },
      { id: "elc_996", year: 5, semester: "Electiva", name: "Materias Electivas", weekly_hours: 10, total_hours: 240, estado: "pendiente", regulares: [], aprobadas: [] },
      { id: "elc_99017", year: 3, semester: "Anual", name: "Hidrodinámica y Neumática", weekly_hours: 0, total_hours: 2, estado: "pendiente", regulares: [], aprobadas: [], isElectiva: true },
      { id: "elc_99018", year: 5, semester: "Anual", name: "Mantenimiento Electromecánico", weekly_hours: 0, total_hours: 3, estado: "pendiente", regulares: [], aprobadas: [], isElectiva: true },
      { id: "elc_99019", year: 5, semester: "Anual", name: "Cálculo y Control de Maq. Eléctrica", weekly_hours: 0, total_hours: 4, estado: "pendiente", regulares: [], aprobadas: [], isElectiva: true },
      { id: "elc_99020", year: 5, semester: "Anual", name: "Máquinas y Equipos Industriales", weekly_hours: 0, total_hours: 4, estado: "pendiente", regulares: [], aprobadas: [], isElectiva: true }
    ]
  }
};